import Head from 'next/head';
import Image from 'next/image';
import axios from 'axios';
import { useState } from 'react';
import { BsSearch } from 'react-icons/bs';
import Spinner from '@/components/Spinner';
import Weather from '@/components/Weather';

export default function Home() {
	const [city, setCity] = useState('');
	const [weather, setWeather] = useState({});
	const [loading, setLoading] = useState(false);

	const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${process.env.NEXT_PUBLIC_WEATHER_KEY}&units=imperial`;

	const fetchWeather = (e) => {
		e.preventDefault();
		setLoading(true);

		axios.get(url).then((response) => {
			setWeather(response.data);
		});
		setCity('');
		setLoading(false);
	};

	if (loading) {
		return <Spinner />;
	} else {
		return (
			<>
				<Head>
					<title>Weather - Next App</title>
					<meta
						name='description'
						content='Generated by create next app'
					/>
					<meta
						name='viewport'
						content='width=device-width, initial-scale=1'
					/>
					<link
						rel='icon'
						href='/favicon.ico'
					/>
				</Head>
				{/* Overlay */}
				<div className='absolute top-0 left-0 right-0 bottom-0 bg-black/40 z-[1]' />
				<Image
					src='https://images.unsplash.com/photo-1607131168055-9ff89d69922f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjZ8fHNjZW5lcnl8ZW58MHx8MHx8&auto=format&fit=crop&w=700&q=60'
					fill
					alt=''
					className='object-cover'
				/>

				{/* Search */}
				<div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 text-white z-10'>
					<form
						onSubmit={fetchWeather}
						className='flex justify-between items-center w-full m-auto p-3 bg-transparent border border-gray-300 text-white rounded-2xl'
					>
						<div>
							<input
								onChange={(e) => setCity(e.target.value)}
								type='text'
								placeholder='Search City'
								className='bg-transparent border-none text-white focus:outline-none text-2xl'
							/>
						</div>
						<button
							className=''
							onClick={fetchWeather}
						>
							<BsSearch size={20} />
						</button>
					</form>
				</div>
				{/* Weather */}

				{weather.main && <Weather data={weather} />}
			</>
		);
	}
}
